### ISSUE TITLE
start but exit with failure

### ISSUE THREAD

**Issue by lampda** [romans-weapon/spark-hadoop-hive-docker#1]
when I used "docker compose up", I got this error:

```bash
starting container process caused: exec: "/usr/sbin/init": stat /usr/sbin/init: no such file or directory: unknown
```

What is this init and what does it do in this context?

**Comment by AnudeepKonaboina** [comment]
@lampda ,

You need to follow the steps in the README file .
you must not start with docker-compose up directly .Instead after cloning you need to execute the setup.sh file .

The init is the init.d script which is used to run systemd inside docker container,in our case we need sshd service.
Hope this helps you.

**Comment by AnudeepKonaboina** [comment]
@lampda ,

did the solution work?

**Comment by lampda** [comment]
It works if I follow the entire steps. Thank you.
